---
title: "class-2020-03-05"
author: "Jamal Nimer"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(googlesheets4)
library(janitor)
library(tidyverse)
library(ggplot2)
library(dplyr)
sheets_deauth()
library(infer)

url <- '14HmwN2cEVAJHupuehCuLdwG9BXtR3COrxDgaaylLhkA'

x <- read_sheet(ss = url) %>% 
  clean_names() %>% 
  mutate(perc_red = red/(red+white)) %>% 
  arrange(desc(perc_red)) 
```

```{r, echo = FALSE}
ggplot(x, aes(perc_red)) + 
  geom_histogram() 
```

```{r, echo = FALSE}
# setting proportion to 20%

urn <- tibble(
  bean_ID = 1:10000,
  color = c(rep('Red', 2000), rep('White', 8000))
)

# sampleurn <- urn %>% 
#   rep_sample_n(size = 25, reps = 51)
# 
#   
# virtual_prop_red <-  sampleurn %>% 
#   group_by(replicate) %>% 
#   summarize(num_red = sum(color == "Red")) %>% 
#   mutate(prop_red = num_red / 25)
#   
# ggplot(virtual_prop_red, aes(x = prop_red)) +
#   geom_histogram(binwidth = 0.05, boundary = 0.4, color = "white") + 
#   labs(x = "Proportion of 25 balls that were red",
#        title = "Distribution of 51 proportions red")


# FUNCTION

sampleurn <- function(x, size, reps) {
  x %>% 
  rep_sample_n(size = size, reps = reps)
}

prop_red <- function(x, size, reps){
sampleurn(x = x, size = size, reps = reps) %>% 
  group_by(replicate) %>% 
  summarize(num_red = sum(color == "Red")) %>% 
  mutate(prop_red = num_red / size)
} 

Jamlsucks <- prop_red(x = urn, size= 25, reps = 1000)

View(Jamlsucks)

# ggplot(virtual_prop_red, aes(prop_red)) +
#   geom_histogram(binwidth = 0.05, boundary = 0.4, color = "white") + 
#   labs(x = "Proportion of x balls that were red",
#        title = "Distribution of y proportions red")

 
# test(25, 1000)
# tibble of all the beads
# sample without replacement 
# calculate the proportion for each row using a maps
# take the mean of the proportion columns
```


